source 'https://rubygems.org'

gem 'bundler'
gem 'rack'
gem 'rake'
gem 'broken_link_finder'

group :development do
  gem 'byebug'
  gem 'maxitest'
  gem 'pry'
  gem 'amazing_print'
  gem 'toys'
  gem 'yard'
end
