source 'https://rubygems.org' do
  gem 'nokogiri'
  gem 'rails', '>=5.0.0'
  gem 'sinatra'
  gem 'thin'
  gem 'json'

  group :development do
    gem 'rb-readline'
    gem 'pry-coolline'
	  gem 'pry'
	  gem 'byebug'
    gem 'hijack'
    gem 'guard'
	end

  # My own personally developed gems.
  group :personal do
    gem 'wgit'
  end
end
